pipeline:
  docker:
    image: plugins/docker:latest
    repo: joshdvir/drone-docker-bash
    tag:
      - "17.05"
      - "17"
      - "latest"
    force_tag: true
    file: Dockerfile
    secrets: [ docker_username, docker_password ]
    when:
      branch: [master]
