# syntax = docker/dockerfile:1.0-experimental
FROM docker:17.05.0-ce-dind

RUN apk add --update --no-cache \
    curl \
    jq \
    ca-certificates \
    bash
WORKDIR /app
RUN --mount=type=secret,id=twistlock_secret (cp /run/secrets/twistlock_secret /app/.secrets)
RUN source /app/.secrets
ADD docker.sh /bin/
ENTRYPOINT ["/usr/local/bin/dockerd-entrypoint.sh", "/bin/docker.sh"]
